name: Update README Hourly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  activity:
    runs-on: ubuntu-latest
    name: Metrics Activity

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generating svg
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.activity.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 0
          plugin_activity_skipped: heitorpolidoro
          output_action: none

      - name: Upload svg
        uses: actions/upload-artifact@v3
        with:
          name: metrics
          path: /metrics_renders/metrics.activity.svg
          retention-days: 1


  update:
    runs-on: ubuntu-latest
    needs:
      - activity

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Download Artefacts
        uses: actions/download-artifact@v3

      - name: Update images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            set -x
            git config http.sslVerify false
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git add -A
            git commit -m "Update README - metrics"
            git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/heitorpolidoro/heitorpolidoro.git" HEAD:master
          else
            echo "Nothing to commit"
          fi

