name: Update README Daily

on:
  push:

jobs:
  overall:
    name: Metrics Overall
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generating svg
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.overall.svg
          token: ${{ secrets.HEITORPOLIDORO_PAT }}
          base_indepth: yes
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          output_action: none

      - name: Upload svg
        uses: actions/upload-artifact@v3
        with:
          name: metrics
          path: /metrics_renders/metrics.overall.svg
          retention-days: 1

  update:
    runs-on: ubuntu-latest
    needs:
      - overall
      - achievements
      - followup

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Download Artefacts
        uses: actions/download-artifact@v3

      - name: Set up Python 3.11
        id: cache_pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build README
        env:
          GITHUB_TOKEN: ${{ secrets.HEITORPOLIDORO_PAT }}
        run: |
          python build_readme.py

      - name: Update images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            set -x
            git config http.sslVerify false
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git add -A
            git commit -m "Update README - metrics"
            git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/heitorpolidoro/heitorpolidoro.git" HEAD:master
          else
            echo "Nothing to commit"
          fi
