name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        id: cache_pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build README
        run: |
          python build_readme.py

      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
#          committer_message: "chore: update metrics"
          token: ${{ secrets.HEITORPOLIDORO_PAT }}
          base: header, activity, community, repositories, metadata
          output_action: none

      - name: Detailed display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.achievements.svg
          token: ${{ secrets.HEITORPOLIDORO_PAT }}
          base: ""
          plugin_achievements: yes
          output_action: none

#      - name: Commit changes
#        uses: lowlighter/metrics@latest
#        run: |
#          set +e
#          git checkout metrics-renders
#          git config user.name github-actions[bot]
#          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
#          sudo mv /metrics_renders/* ./
#          git add --all
#          git commit -m "chore: update metrics"
#          git push
      - name: Update README.md
        env:
          GITHUB_TOKEN=${{ secrets.HEITORPOLIDORO_PAT }}
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            set -x
            git config http.sslVerify false
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git add -A
            git commit -m "Update README"
            git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/heitorpolidoro/heitorpolidoro.git" HEAD:master
          fi
#            git remote add origin git@github.com:heitorpolidoro/heitorpolidoro.git
#
#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: "Update README"
#          commit_user_name: README Bot
#          commit_user_email: readme[bot]@users.noreply.github.com"
