name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
#    permissions:
#        contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - run: pip install -r requirements.txt
      - name: Build README
#        env:
#          GITHUB_TOKEN: ${{ secrets.HEITORPOLIDORO_PAT }}
        run: |
          python build_readme.py

      - name: Example
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.HEITORPOLIDORO_PAT }}
          base: header, repositories
          plugin_lines: yes

      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          set -x
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git remote set-url origin https://github.com/heitorpolidoro/heitorpolidoro.git
          git add .
          git commit -m "Update README"
          git push
          fi
#
#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: "Update README"
#          commit_user_name: README Bot
#          commit_user_email: readme[bot]@users.noreply.github.com"
