name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.HEITORPOLIDORO_PAT }}
          base: header, activity, community, repositories, metadata
          output_action: none

      - name: Detailed display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.achievements.svg
          token: ${{ secrets.HEITORPOLIDORO_PAT }}
          base: ""
          plugin_achievements: yes
          output_action: none

      - name: Opened on user's repositories
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.HEITORPOLIDORO_PAT }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes

      - name: Update README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            set -x
            git config http.sslVerify false
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git add -A
            git commit -m "Update README - metrics"
            git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/heitorpolidoro/heitorpolidoro.git" HEAD:master
          else
            echo "Nothing to commit"
          fi
