name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
#    permissions:
#        contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - run: pip install -r requirements.txt
      - name: Build README
        env:
          GITHUB_TOKEN: ${{ secrets.HEITORPOLIDORO_PAT }}
        run: |
          python build_readme.py

#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: "Update README"
#          commit_user_name: README Bot
#          commit_user_email: readme[bot]@users.noreply.github.com"

      - name: Create README.md
        uses: actions-js/profile-readme@master
        with:
          username: heitorpolidoro
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
